version: '3.3'

networks: 
    cdr_net:
        driver: bridge

services:
    db:
        # image: nimmis/alpine-mariadb
        image: mysql:5
        # container_name: mariadb
        container_name: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=pwdroot
            - MYSQL_DATABASE=asteriskcdrdb
            - MYSQL_USER=cdrdb
            - MYSQL_PASSWORD=cdrpwd
        ports: 
            - '13306:3306'
        volumes:
            - webcdr_db_data:/data
        restart: always
        networks: 
            - 'cdr_net'

    cdr:
        build: .
        container_name: webcdr
        environment: 
            - TZ=America/Sao_Paulo
            - DB_CLIENT=mysql
            - DB_CONNECTION_HOST=db
            - DB_CONNECTION_USER=cdrdb
            - DB_CONNECTION_PASSWORD=cdrpwd
            - DB_CONNECTION_DATABASE=asteriskcdrdb
            - DB_CONNECTION_CHARSET=utf8
            - CDR_TABLE=cdr
            - SESSION_KEY=123hjhfds7&&&kjfh&&&788
            - AUTH_AD_DOMAIN=exemple
            - AUTH_AD_CONNECTION_URL=ldap://server.ip.address
            - AUTH_AD_CONNECTION_BASEDN=dc=example,dc=org
            - AUTH_AD_CONNECTION_USERNAME=cdruser@example.org
            - AUTH_AD_CONNECTION_PASSWORD=cdruser_ad_password
        ports: 
            - '9030:9030'
        volumes:
            - webcdr_web_data:/var/spool/asterisk/monitor
        depends_on: 
            - db
        restart: always
        networks: 
            - 'cdr_net'

volumes:
    webcdr_db_data:
    webcdr_web_data:
    